### ISSUE TITLE
add overall api client rate limit option

### ISSUE THREAD

**Issue by creharmony** [creharmony/node-etsy-client#19]
As Etsy limits the number of call per time window,

It would be great to have an option to calibrate client calls rate limit to never reach allowed api key rate limit.

- option must be disabled by default
- option must be configured by options
- options must permit "per second" and/or "per day" windows
- study retry after option in case of error (another issue to implement retry?)

---
- [Etsy rate limit documentation](https://www.etsy.com/developers/documentation/getting_started/api_basics#section_rate_limiting)

**Comment by boly38** [comment]
- [request-rate-limiter](https://github.com/linaGirl/request-rate-limiter) - pro : top seo, very easy to implement // con : embeds experimental-modules, enforce "module" type

**Comment by boly38** [comment]
Using a rate limit of 10/sec make etsy error

````
You have exceeded your quota of: 10 requests per 1 second(s) for public requests.
````


So following this, I made some additional test : 
````
/**                           duration
    200 queries at 10/sec |=> 19sec   =~ 10.52 /sec
    200 queries at  9/sec |=> 21.228  =~ 9.4215/sec
    200 queries at  8/sec |=> 24      =~ 8.33  /sec
    200 queries at  7/sec |=> 27.579  =~ 7.2519/sec
 */`
````

Intensive use of etsy client with a rate set to 8 per second seems ok to fix etsy limit issue.

Either Etsy or rate limiter is lying ;)

**Comment by creharmony** [comment]
- update susi-rali following creharmony/susi-rali#3 maxProcessing
