### ISSUE TITLE
TypeScript type declaration file

### ISSUE THREAD

**Issue by geopic** [creharmony/node-etsy-client#3]
If you want I can write a TypeScript type declaration file for this package so that TS developers can utilise the type-checking feature of the language as they use this package. Let me know if you are interested.

**Comment by boly38** [comment]
Hi, sure it would be great if this package could be imported in both cases(JS & TS). You could submit a PR.

**Comment by geopic** [comment]
Awesome, I'll start on it tomorrow then.

**Comment by creharmony** [comment]
fixed in `0.0.1`
