### ISSUE TITLE
Improvement: Update Etsy API to v3

### ISSUE THREAD

**Issue by icemansparks** [creharmony/node-etsy-client#39]
Since etsys API v2 will be discontinued and stop working by the end of the year as stated in the etsy documentation ( https://www.etsy.com/developers/documentation/getting_started/edd#section_update_your_app ), it would be wise to update the client to use etsys new v3 API - which is similar but not exactly the same.

Details can be found here:
https://developers.etsy.com/documentation/

Great job here btw! It's nice to see an updated etsy node client.

**Comment by creharmony** [comment]
🧑‍💼 I start to work on it because there is a date for end of v2..

I'll put down here some dev remarks during dev.

---

v2 findAllShops (no mandatory arg) => v3 **findShops** (shop_name required)

- bug [limit:2 return 3 results](https://github.com/etsy/open-api/issues/420)
- *WIP*
